/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module multiple_modules(a, b, c, y);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  wire net1;
  wire \u1.a ;
  wire \u1.b ;
  wire \u1.y ;
  wire \u2.a ;
  wire \u2.b ;
  wire \u2.y ;
  output y;
  wire y;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(b),
    .B(a),
    .X(\u1.y )
  );
  sky130_fd_sc_hd__or2_0 _1_ (
    .A(c),
    .B(\u1.y ),
    .X(y)
  );
  assign \u2.y  = y;
  assign \u2.b  = c;
  assign \u2.a  = \u1.y ;
  assign \u1.a  = a;
  assign \u1.b  = b;
  assign net1 = \u1.y ;
endmodule
