/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module incomp_if(i0, i1, i2, y);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  output y;
  reg y;
  always @*
    if (i0) y = i1;
endmodule
