/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dff_asyncres(clk, async_reset, d, q);
  wire _0_;
  input async_reset;
  wire async_reset;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  assign _0_ = ~async_reset;
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(d),
    .Q(q),
    .RESET_B(_0_)
  );
endmodule
