/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dff_async_set(clk, async_set, d, q);
  wire _0_;
  input async_set;
  wire async_set;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  assign _0_ = ~async_set;
  sky130_fd_sc_hd__dfstp_2 _2_ (
    .CLK(clk),
    .D(d),
    .Q(q),
    .SET_B(_0_)
  );
endmodule
