/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dff_syncres(clk, async_reset, sync_reset, d, q);
  wire _0_;
  input async_reset;
  wire async_reset;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  input sync_reset;
  wire sync_reset;
  sky130_fd_sc_hd__dfxtp_1 _1_ (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
  assign _0_ = sync_reset ? 1'h0 : d;
endmodule
